// ============================================================
// Codebook ROM — Stores D-bit random binary vectors for Q levels
// ============================================================
// Two instances needed: one for channel A (amplitude), one for B (phase-diff).
// Each entry is D bits wide, stored as NUM_CHUNKS × CHUNK_W words.
//
// Address = level_index * NUM_CHUNKS + chunk_index
//
// Initialization: loaded from .hex file generated by Python export
//
// FPGA: Inferred as Block RAM (read-only port usage).
//       For Q=16, NUM_CHUNKS=128, CHUNK_W=32:
//       Depth = 16 * 128 = 2048 words × 32 bits = 8 KB → 2 BRAM36
// ============================================================

module codebook_rom #(
    parameter DEPTH    = 2048,          // Q * NUM_CHUNKS
    parameter ADDR_W   = 11,            // ceil(log2(DEPTH))
    parameter DATA_W   = 32,            // CHUNK_W
    parameter HEX_FILE = "codebook.hex" // Initialization file
)(
    input  wire                clk,
    input  wire [ADDR_W-1:0]  addr,
    output reg  [DATA_W-1:0]  data_out
);

    // Block RAM inference (read-only)
    (* ram_style = "block" *)
    reg [DATA_W-1:0] mem [0:DEPTH-1];

    // Initialize from hex file
    initial begin
        $readmemh(HEX_FILE, mem);
    end

    // Synchronous read (1 cycle latency)
    always @(posedge clk) begin
        data_out <= mem[addr];
    end

endmodule
