// =============================================================================
// Testbench: 3-Level Haar Wavelet Decomposition
// =============================================================================
// Reads test vectors generated by Python, feeds them to the DUT,
// and compares output sub-bands against expected values.
// =============================================================================

`timescale 1ns / 1ps

module tb_haar_wavelet_3lvl;

    // ─── Parameters ───
    localparam CLK_PERIOD = 10;   // 100 MHz
    localparam N_SAMPLES  = 187;
    localparam N_CD1      = 94;
    localparam N_CD2      = 47;
    localparam N_CD3      = 24;
    localparam N_CA3      = 24;
    localparam N_VECTORS  = 10;

    // ─── Clock / Reset ───
    reg clk, rst_n;
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // ─── DUT signals ───
    reg         start;
    reg  signed [7:0]  sample_in;
    reg         sample_valid;
    wire        busy, done;
    reg  [6:0]  rd_addr;
    wire signed [9:0]  cD1_out;
    wire signed [10:0] cD2_out;
    wire signed [11:0] cD3_out;
    wire signed [11:0] cA3_out;

    // ─── DUT ───
    haar_wavelet_3lvl dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .i_start        (start),
        .i_sample       (sample_in),
        .i_sample_valid (sample_valid),
        .o_busy         (busy),
        .o_done         (done),
        .i_rd_addr      (rd_addr),
        .o_cD1          (cD1_out),
        .o_cD2          (cD2_out),
        .o_cD3          (cD3_out),
        .o_cA3          (cA3_out)
    );

    // ─── Test vector storage ───
    reg [7:0]  input_mem  [0:N_VECTORS*N_SAMPLES-1];
    reg [9:0]  cD1_exp    [0:N_VECTORS*N_CD1-1];
    reg [10:0] cD2_exp    [0:N_VECTORS*N_CD2-1];
    reg [11:0] cD3_exp    [0:N_VECTORS*N_CD3-1];
    reg [11:0] cA3_exp    [0:N_VECTORS*N_CA3-1];

    initial begin
        $readmemh("test_vectors/wavelet_input.mem",        input_mem);
        $readmemh("test_vectors/wavelet_cD1_expected.mem", cD1_exp);
        $readmemh("test_vectors/wavelet_cD2_expected.mem", cD2_exp);
        $readmemh("test_vectors/wavelet_cD3_expected.mem", cD3_exp);
        $readmemh("test_vectors/wavelet_cA3_expected.mem", cA3_exp);
    end

    // ─── Test ───
    integer vec, i, errors;
    reg signed [9:0]  exp_cD1;
    reg signed [10:0] exp_cD2;
    reg signed [11:0] exp_cD3;
    reg signed [11:0] exp_cA3;

    initial begin
        $dumpfile("tb_haar_wavelet_3lvl.vcd");
        $dumpvars(0, tb_haar_wavelet_3lvl);

        // Reset
        rst_n = 0;
        start = 0;
        sample_in = 0;
        sample_valid = 0;
        rd_addr = 0;
        errors = 0;

        repeat (5) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        for (vec = 0; vec < N_VECTORS; vec = vec + 1) begin
            $display("--- Test vector %0d ---", vec);

            // Start
            @(posedge clk);
            start = 1;
            @(posedge clk);
            start = 0;

            // Feed 187 samples (one per clock)
            for (i = 0; i < N_SAMPLES; i = i + 1) begin
                @(posedge clk);
                sample_in    = $signed(input_mem[vec * N_SAMPLES + i]);
                sample_valid = 1;
            end
            @(posedge clk);
            sample_valid = 0;
            sample_in    = 0;

            // Wait for done
            wait (done == 1);
            @(posedge clk);

            // Check cD1 (94 values)
            for (i = 0; i < N_CD1; i = i + 1) begin
                rd_addr = i[6:0];
                @(posedge clk);  // allow read
                exp_cD1 = $signed(cD1_exp[vec * N_CD1 + i]);
                if (cD1_out !== exp_cD1) begin
                    $display("  ERROR cD1[%0d]: got %0d, expected %0d", i, cD1_out, exp_cD1);
                    errors = errors + 1;
                end
            end

            // Check cD2 (47 values)
            for (i = 0; i < N_CD2; i = i + 1) begin
                rd_addr = i[6:0];
                @(posedge clk);
                exp_cD2 = $signed(cD2_exp[vec * N_CD2 + i]);
                if (cD2_out !== exp_cD2) begin
                    $display("  ERROR cD2[%0d]: got %0d, expected %0d", i, cD2_out, exp_cD2);
                    errors = errors + 1;
                end
            end

            // Check cD3 (24 values)
            for (i = 0; i < N_CD3; i = i + 1) begin
                rd_addr = i[6:0];
                @(posedge clk);
                exp_cD3 = $signed(cD3_exp[vec * N_CD3 + i]);
                if (cD3_out !== exp_cD3) begin
                    $display("  ERROR cD3[%0d]: got %0d, expected %0d", i, cD3_out, exp_cD3);
                    errors = errors + 1;
                end
            end

            // Check cA3 (24 values)
            for (i = 0; i < N_CA3; i = i + 1) begin
                rd_addr = i[6:0];
                @(posedge clk);
                exp_cA3 = $signed(cA3_exp[vec * N_CA3 + i]);
                if (cA3_out !== exp_cA3) begin
                    $display("  ERROR cA3[%0d]: got %0d, expected %0d", i, cA3_out, exp_cA3);
                    errors = errors + 1;
                end
            end

            if (errors == 0)
                $display("  PASS");
        end

        $display("");
        if (errors == 0)
            $display("=== ALL %0d TEST VECTORS PASSED ===", N_VECTORS);
        else
            $display("=== FAILED: %0d errors ===", errors);

        $finish;
    end

endmodule
